[package]
name = "cb-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cb-common.workspace = true
cb-pbs.workspace = true
cb-crypto.workspace = true
cb-metrics.workspace = true

alloy.workspace = true

tokio.workspace = true

serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

tracing.workspace = true
clap.workspace = true

eyre.workspace = true

tree_hash.workspace = true
tree_hash_derive.workspace = true

bollard.workspace = true
docker-compose-types.workspace = true
dotenvy.workspace = true
indexmap.workspace = true
