{
 "title": "PBS Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": "register_validator, get_header, submit_blinded_block"
   }
  ]
 },
 "panels": [
  {
   "title": "Last delivered slot",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cb_pbs_relay_last_slot", "legendFormat": "{{relay_id}}" }
   ]
  },
  { "title": "$endpoint calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "endpoint" },
  {
   "title": "$endpoint Relay Success QPH",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(cb_pbs_relay_status_code_total{http_status_code=~\"2..\", endpoint=\"$endpoint\"}[1h])) by (relay_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Relay Error QPH",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(cb_pbs_relay_status_code_total{http_status_code=~\"4..|5..\", endpoint=\"$endpoint\"}[1h])) by (relay_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Beacon Node Success QPH",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(cb_pbs_beacon_node_status_code_total{http_status_code=~\"2..\", endpoint=\"$endpoint\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Beacon Node Error QPH",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(cb_pbs_beacon_node_status_code_total{http_status_code=~\"4..|5..\", endpoint=\"$endpoint\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Relay P50",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cb_pbs_relay_latency_bucket{endpoint=\"$endpoint\"}[1m])) by (le, relay_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Relay P90",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(cb_pbs_relay_latency_bucket{endpoint=\"$endpoint\"}[1m])) by (le, relay_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Relay P99",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cb_pbs_relay_latency_bucket{endpoint=\"$endpoint\"}[1m])) by (le, relay_id))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}