{
 "title": "Signer Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": "get_pubkeys, generate_proxy_key, request_signature"
   }
  ]
 },
 "panels": [
  {
   "title": "Proxy delegations requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cb_signer_signer_status_code_total{endpoint=\"generate_proxy_key\", http_status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "Commitments signed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cb_signer_signer_status_code_total{endpoint=\"request_signature\", http_status_code=\"200\"}"
    }
   ]
  },
  { "title": "$endpoint calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "endpoint" },
  {
   "title": "$endpoint Success QPH",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(cb_signer_signer_status_code_total{http_status_code=~\"2..\", endpoint=\"$endpoint\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$endpoint Error QPH",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "increase(cb_signer_signer_status_code_total{http_status_code=~\"4..|5..\", endpoint=\"$endpoint\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}