apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commit-boost.fullname" . }}
  labels:
    {{- include "commit-boost.labels" . | nindent 4 }}
data:
  {{- if .Values.commitBoost.pbs.enable }}
  config.pbs.toml: |-
    {{ .Values.commitBoost.pbs.config | nindent 4 }}
  {{- end }}

  prometheus.yaml: ""
