apiVersion: v1
kind: Service
metadata:
  name: {{ include "commit-boost.fullname" . }}
  labels:
    {{- include "commit-boost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http-pbs
      targetPort: http-pbs
      protocol: TCP
    - port: {{ .Values.service.metrics_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    {{- include "commit-boost.selectorLabels" . | nindent 4 }}
