# PBS config with a custom chain spec file

# genesis time in seconds needs to be specified
chain = { genesis_time_secs = 100, path = "tests/data/holesky_spec.json" }

[pbs]
port = 18550

[[relays]]
id = "example-relay"
url = "http://0xa1cec75a3f0661e99299274182938151e8433c61a19222347ea1313d839229cb4ce4e3e5aa2bdeb71c8fcf1b084963c2@abc.xyz"
