[package]
name = "da_commit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
commit-boost = { path = "../../bin" }

alloy.workspace = true

reqwest.workspace = true
tokio.workspace = true

# tree_hash.workspace = true
serde.workspace = true

tracing.workspace = true
eyre.workspace = true
prometheus.workspace = true
lazy_static.workspace = true
