name: CI

on:
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-02-26
          components: clippy, rustfmt

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Setup just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.5.0

      - name: Check compilation
        run: cargo check

      - name: Check formatting
        run: just fmt-check

      - name: Check clippy
        run: just clippy

      - name: Run tests
        run: just test
