name: CI

on:
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-01-01
          components: clippy, rustfmt

      - name: Install protoc
        run: sudo provisioning/protoc.sh

      - name: Install just
        run: cargo install just --version 1.40.0 --locked
        env:
          CARGO_TARGET_DIR: /tmp/cargo-install-just

      - name: Add cargo bin to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Check compilation
        run: cargo check

      - name: Check formatting
        run: just fmt-check

      - name: Check clippy
        run: just clippy

      - name: Run tests
        run: just test
