name: Deploy Images to GHCR


on:
  push:
    branches: ['**']
  pull_request:
    branches:
      - main
      - '**'

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build pbs image'
        run: |
          docker build --tag ghcr.io/commit-boost/commit-boost-client/pbs:latest -f docker/pbs.Dockerfile .
          docker push ghcr.io/commit-boost/commit-boost-client/pbs:latest