name: Security Audit
on:
  pull_request:
    paths: [Cargo.lock]
  push:
    branches: [main]
    paths: [Cargo.lock]
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  checks: write
  pull-requests: read
  contents: read

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
        with:
          tool: cargo-audit
      - run: cargo audit